name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm install
      - name: Run TypeScript
        run: tsc --noEmit
      - name: Run ESLint
        run: eslint ./src --ext .js,.jsx,.ts,.tsx
