[tools]
node = "22.21.1"
# Npm tools
npm = "11.11.0"
"npm:@devcontainers/cli" = "0.83.2"
"npm:eas-cli" = "16.32.0"
# Aqua tools
"aqua:opencode" = "1.1.63"
"aqua:pnpm" = "10.30.1"
"aqua:cli/cli" = "2.88.1"
