packages: []
overrides:
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'

storeDir: /Users/dzaitsev/.local/share/pnpm/store

supportedArchitectures:
  cpu: [ arm64 ]
  os: [ darwin, linux ]

trustPolicy: off
